In [48]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)

In [135]:
# Training
train=pd.read_csv('train.csv')
train.head(3)

,ID,year_of_poll,own_self_emp,veteran benefits,currently_enrolled,race,father_country,educ,house_stat,major_ind_code,labour_union,self_country,major_occ_code,age,mother_country,house_summary,gender,hisp_origin,gains,dividends,marriage_status,losses,employer_of,house_1yr_ago,income_filled,weeks_worked,under18,hourly_wage,unemp_reason,citizenship,woker_type,fed_liability,full_partime_job,income
0,0,2004,0,2,High school,White,United-States,Associates degree-academic program,Householder,Business and repair services,no,United-States,Protective services,42,United-States,Householder,M,All_Other,0.0,0.0,Married_civilian_Sp_Pr,0.0,1,No,No,47,NaN,0.0,NaN,NB_US,Pvt,Joint_both_under65,Children/Armed_Forces,More than 50K $
1,1,2005,0,0,College/University,White,Japan,Children,Child <18 never marr not in subfamily,Not in universe or children,NaN,United-States,NaN,10,United-States,Child_U18_Unmarried,M,Mex_Amer,0.0,0.0,Unmarried,0.0,0,NaN,No,0,Both_Pr,0.0,NaN,NB_US,NaN,Nonfiler,Children/Armed_Forces,More than 50K $
2,2,2004,0,2,NaN,White,United-States,Some college but no degree,Secondary individual,Manufacturing-durable goods,NaN,United-States,Machine operators assmblrs & inspctrs,46,United-States,Non_Relative,M,All_Other,0.0,0.0,Divorced,0.0,6,No,Yes,47,NaN,0.0,NaN,NB_US,Pvt,Single,Children/Armed_Forces,More than 50K $

In [136]:
# Testing 
test=pd.read_csv('test.csv')
test.head(3)

,ID,year_of_poll,own_self_emp,veteran benefits,currently_enrolled,race,father_country,educ,house_stat,major_ind_code,labour_union,self_country,major_occ_code,age,mother_country,house_summary,gender,hisp_origin,gains,dividends,marriage_status,losses,employer_of,house_1yr_ago,income_filled,weeks_worked,under18,hourly_wage,unemp_reason,citizenship,woker_type,fed_liability,full_partime_job
0,105000,2005,0,2,College/University,White,United-States,Some college but no degree,Householder,Manufacturing-nondurable goods,NaN,United-States,Precision production craft & repair,32.0,United-States,Householder,M,All_Other,0.0,0.0,Married_civilian_Sp_Pr,0.0,6,NaN,No,47,NaN,0.0,NaN,NB_US,Pvt,Joint_both_under65,Full-time schedules
1,105001,2004,0,2,College/University,White,United-States,Bachelors degree(BA AB BS),Nonfamily householder,Medical except hospital,NaN,United-States,Professional specialty,51.0,United-States,Householder,F,All_Other,0.0,120.0,Unmarried,0.0,6,Yes,NaN,47,NaN,0.0,NaN,NB_US,Pvt,Single,Children/Armed_Forces
2,105002,2004,0,2,NaN,White,United-States,7th and 8th grade,In group quarters,Not in universe or children,no,United-States,NaN,70.0,United-States,Sy_Individual,F,All_Other,0.0,0.0,Widowed,0.0,0,Yes,NaN,0,NaN,0.0,NaN,NB_US,NaN,Nonfiler,Children/Armed_Forces

In [137]:
# Split of data
x_train,y_train=train.drop(columns=['income']),train['income']
x_test=test.copy()

In [52]:
# Check for Null values
d=x_train.isnull().sum()/len(x_train)*100

In [53]:
d.values[d.values>1]

array([29.94571429, 33.64857143, 50.52857143, 50.78285714, 30.86      ,
       72.39619048, 96.96285714, 50.31904762,  1.32571429])

In [54]:
x_test.isnull().sum()/len(x_test)*100

ID                     0.000000
year_of_poll           0.000000
own_self_emp           0.000000
veteran benefits       0.000000
currently_enrolled    30.030952
race                   0.000000
father_country         0.000000
educ                   0.000000
house_stat             0.007143
major_ind_code         0.000000
labour_union          34.135714
self_country           0.000000
major_occ_code        50.161905
age                    1.419048
mother_country         0.000000
house_summary          0.000000
gender                 0.000000
hisp_origin            0.000000
gains                  0.000000
dividends              0.000000
marriage_status        0.000000
losses                 0.000000
employer_of            0.000000
house_1yr_ago         50.947619
income_filled         30.971429
weeks_worked           0.000000
under18               72.238095
hourly_wage            0.000000
unemp_reason          96.940476
citizenship            0.000000
woker_type            49.945238
fed_liability          0.000000
full_partime_job       1.352381
dtype: float64

In [138]:
# Dropping of Column
x_train.drop(columns=['currently_enrolled','labour_union','major_occ_code','house_1yr_ago',
                      'income_filled','under18','unemp_reason','woker_type'],inplace=True)

In [139]:
# Dropping of Column
x_test.drop(columns=['currently_enrolled','labour_union','major_occ_code','house_1yr_ago',
                      'income_filled','under18','unemp_reason','woker_type'],inplace=True)

In [57]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()

In [61]:
dummy=[]
ord1=[]
for i in x_train.describe(include='object').columns:
    if x_train[i].nunique()>3:
        ord1.append(i) 
    else:
        dummy.append(i)

In [63]:
dummy

['gender']

In [144]:
x_train=pd.get_dummies(columns=['gender'],data=x_train,drop_first=True)
x_test=pd.get_dummies(columns=['gender'],data=x_test,drop_first=True)

KeyError: "None of [Index(['gender'], dtype='object')] are in the [columns]"

In [145]:
x_train

,ID,year_of_poll,own_self_emp,veteran benefits,race,father_country,educ,house_stat,major_ind_code,self_country,age,mother_country,house_summary,hisp_origin,gains,dividends,marriage_status,losses,employer_of,weeks_worked,hourly_wage,citizenship,fed_liability,full_partime_job,gender_M
0,0,2004,0,2,White,United-States,Associates degree-academic program,Householder,Business and repair services,United-States,42,United-States,Householder,All_Other,0.0,0.0,Married_civilian_Sp_Pr,0.0,1,47,0.0,NB_US,Joint_both_under65,Children/Armed_Forces,1
1,1,2005,0,0,White,Japan,Children,Child <18 never marr not in subfamily,Not in universe or children,United-States,10,United-States,Child_U18_Unmarried,Mex_Amer,0.0,0.0,Unmarried,0.0,0,0,0.0,NB_US,Nonfiler,Children/Armed_Forces,1
2,2,2004,0,2,White,United-States,Some college but no degree,Secondary individual,Manufacturing-durable goods,United-States,46,United-States,Non_Relative,All_Other,0.0,0.0,Divorced,0.0,6,47,0.0,NB_US,Single,Children/Armed_Forces,1
3,3,2004,0,2,Amer/Indian/Aleut/Eskimo,United-States,High school graduate,Householder,Wholesale trade,United-States,35,United-States,Householder,All_Other,0.0,0.0,Married_civilian_Sp_Pr,0.0,2,47,0.0,NB_US,Joint_both_under65,Children/Armed_Forces,1
4,4,2004,0,2,White,United-States,High school graduate,Householder,Wholesale trade,United-States,61,United-States,Householder,All_Other,0.0,0.0,Divorced,0.0,3,47,0.0,NB_US,Single,Children/Armed_Forces,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104995,104995,2005,2,2,White,United-States,High school graduate,Householder,Not in universe or children,United-States,72,United-States,Householder,All_Other,0.0,450.0,Married_civilian_Sp_Pr,0.0,1,47,0.0,NB_US,Nonfiler,Not in labor force,1
104996,104996,2004,0,0,White,United-States,Children,Child <18 never marr not in subfamily,Not in universe or children,United-States,3,United-States,Child_U18_Unmarried,Mex_Amer,0.0,0.0,Unmarried,0.0,0,0,0.0,NB_US,Nonfiler,Children/Armed_Forces,1
104997,104997,2004,0,2,White,United-States,High school graduate,Nonfamily householder,Manufacturing-nondurable goods,United-States,48,United-States,Householder,All_Other,0.0,0.0,Unmarried,0.0,5,47,1693.2,NB_US,Single,Children/Armed_Forces,0
104998,104998,2005,0,2,White,Italy,High school graduate,Nonfamily householder,Not in universe or children,United-States,88,Italy,Householder,All_Other,0.0,240.0,Widowed,0.0,0,0,0.0,NB_US,Nonfiler,Not in labor force,0
104999,104999,2005,0,0,White,United-States,Children,Child <18 never marr not in subfamily,Not in universe or children,United-States,10,United-States,Child_U18_Unmarried,All_Other,0.0,0.0,Unmarried,0.0,0,0,0.0,NB_US,Nonfiler,Children/Armed_Forces,1

In [142]:
# Fill the null values
from sklearn.impute import KNNImputer
knni=KNNImputer()

In [143]:
knni.fit(x_train,y_train)

ValueError: could not convert string to float: ' White'

In [73]:
# Null values

x_train=pd.DataFrame(data=knni.transform(x_train),columns=x_train.columns)
x_test=pd.DataFrame(data=knni.transform(x_test),columns=x_test.columns)

In [95]:
y_train.replace({'Less than 50K $':0,'More than 50K $':1},inplace=True)

In [81]:
x_train.drop(columns=['ID'],inplace=True)
x_test.drop(columns=['ID'],inplace=True)

In [96]:
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()

In [97]:
logit.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [98]:
y_pred=logit.predict(x_test)

In [99]:
logit.score(x_train,y_train)

0.6341809523809524

In [100]:
from sklearn.metrics import roc_auc_score

In [101]:
sub=pd.read_csv('Sample_Submission.csv')

In [103]:
sub['income']=y_pred

In [110]:
sub.to_csv('Submission.csv',index=False)

In [112]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsTransformer
from sklearn.pipeline import Pipeline

In [115]:
pipe=Pipeline((
('tr',KNeighborsTransformer()),
('kn',KNeighborsClassifier())

))

In [118]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('tr', KNeighborsTransformer()),
                ('kn', KNeighborsClassifier())])

In [119]:
y_pred=pipe.predict(x_test)

In [120]:
sub['income']=y_pred

In [121]:
sub.to_csv('Submission1.csv',index=False)

In [126]:
train.head(2)

,ID,year_of_poll,own_self_emp,veteran benefits,currently_enrolled,race,father_country,educ,house_stat,major_ind_code,labour_union,self_country,major_occ_code,age,mother_country,house_summary,gender,hisp_origin,gains,dividends,marriage_status,losses,employer_of,house_1yr_ago,income_filled,weeks_worked,under18,hourly_wage,unemp_reason,citizenship,woker_type,fed_liability,full_partime_job,income
0,0,2004,0,2,High school,White,United-States,Associates degree-academic program,Householder,Business and repair services,no,United-States,Protective services,42,United-States,Householder,M,All_Other,0.0,0.0,Married_civilian_Sp_Pr,0.0,1,No,No,47,NaN,0.0,NaN,NB_US,Pvt,Joint_both_under65,Children/Armed_Forces,1
1,1,2005,0,0,College/University,White,Japan,Children,Child <18 never marr not in subfamily,Not in universe or children,NaN,United-States,NaN,10,United-States,Child_U18_Unmarried,M,Mex_Amer,0.0,0.0,Unmarried,0.0,0,NaN,No,0,Both_Pr,0.0,NaN,NB_US,NaN,Nonfiler,Children/Armed_Forces,1

In [129]:
col=['year_of_poll', 'own_self_emp', 'veteran benefits', 'race',
       'father_country', 'educ', 'house_stat', 'major_ind_code',
       'self_country', 'age', 'mother_country', 'house_summary', 'hisp_origin',
 'marriage_status', 'employer_of','citizenship', 'fed_liability',
       'full_partime_job', 'gender_M']

In [132]:
from sklearn.tree import DecisionTreeClassifier

In [146]:
from feature_engine.encoding import WoEEncoder
pipe=Pipeline((
('wo',WoEEncoder(variables=list(col))),
('de',DecisionTreeClassifier()),
))

In [147]:
pipe.fit(x_train,y_train)

TypeError: Some of the variables are not categorical. Please cast them as categorical or object before using this transformer.